shop/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("catalogo", views.catalogo, name="catalogo"),
]

tienda-only/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views


urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", include("shop.urls")),
    path("admin/", admin.site.urls),
]

shop/models.py
from django.db import models


class Remera(models.Model):
    marca = models.CharField("Marca", max_length=128)
    TALLES = (
        (1, "XS"),
        (2, "S"),
        (3, "M"),
        (4, "L"),
        (5, "XL"),
        (6, "XXL")
    )
    talle = models.PositiveSmallIntegerField("Talle", choices=TALLES)
    color = models.CharField("Color", max_length=128)
    lisa = models.BooleanField("Lisa")
    GENEROS = (
        (1, "Hombre"),
        (2, "Mujer"),
        (3, "Unisex")
    )
    genero = models.PositiveSmallIntegerField("Género", choices=GENEROS)

    def __str__(self):
        return f"{self.marca} {self.color} {self.get_talle_display()}"

shop/views.py
from django.shortcuts import render

from .models import Remera


def catalogo(request):
    remeras = Remera.objects.all()
    ctx = {"remeras": remeras}
    return render(request, "shop/catalogo.html", ctx)


def index(request):
    return render(request, "shop/index.html")

shop/templates/shop/base.html
{% load static %}
<html>

<head>
<link rel="icon" href="{% static 'shop/icon.png' %}">
  <title>
    Tienda de Indumentaria Online
  </title>
  <link rel="stylesheet" href="{% static 'shop/style.css' %} ?v={{ timestamp }}">
</head>


<header>
  <nav class="navbar">
    <img class="icon" src="{% static 'shop/icon.png' %}" />
    <h1>Tienda de indumentarias</h1>

    <ul class="nav-list">
      <li><a href="{% url 'index' %}">Inicio</a></li>
      <li><a href="{% url 'catalogo' %}">Catálogo</a></li>
      <li><a href="#contacto">Contacto</a></li>
    </ul>
  </nav>
</header>

<body>
  {% block content %}

  {% endblock %}

</body>

<footer id="contacto">
  <h1>Contacto</h1>
  <p><strong>Dirección</strong>: Av. Alverdi 1315</p>
  <p><strong>Teléfono</strong>: +54 9 3735 121314</p>
  <p><strong>Email</strong>: contacto@tienda-only.com
</footer>

</html>

shop/templates/shop/catalogo.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Catalogo{% endblock %}

{% block content %}
<h3>Catálogo</h3>
<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Talle</th>
      <th>Color</th>
      <th>Lisa</th>
      <th>Género</th>
    </tr>
  </thead>
  {% for remera in remeras %}
  <tr>
    <td>{{ remera.marca }}</td>
    <td>{{ remera.get_talle_display }}</td>
    <td>{{ remera.color }}</td>
    <td>
      {% if remera.lisa %}
      Sí
      {% else %}
      No
      {% endif %}
    </td>
    <td>{{ remera.get_genero_display }}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

shop/templates/shop/index.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}
<div class="hero">
    <img class="img-hero" src="{% static 'shop/hero.png' %}" alt="">
    <h1>¡Bienvenido a nuestro sitio!</h1>
</div>

<p class="presentacion">
    En nuestra tienda de indumentaria encontrarás una cuidada selección de prendas de excelente calidad, con variedad de
    talles y estilos para todos los gustos. Trabajamos con marcas reconocidas como Lacoste, Nike, Jaguar y muchas otras,
    ofreciendo productos originales a precios accesibles. Ya sea que busques ropa deportiva, urbana o clásica, te
    garantizamos una experiencia de compra cómoda, confiable y pensada para vos.
</p>


{% endblock %}

shop/templates/shop/inicio.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Inicio{% endblock %}

{% block content %}
<div class="hero">
    <img class="img-hero" src="{% static 'shop/hero.png' %}" alt="">
    <h1>¡Bienvenido a nuestro sitio!</h1>
</div>

<p class="presentacion">
    En nuestra tienda de indumentaria encontrarás una cuidada selección de prendas de excelente calidad, con variedad de
    talles y estilos para todos los gustos. Trabajamos con marcas reconocidas como Lacoste, Nike, Jaguar y muchas otras,
    ofreciendo productos originales a precios accesibles. Ya sea que busques ropa deportiva, urbana o clásica, te
    garantizamos una experiencia de compra cómoda, confiable y pensada para vos.
</p>


{% endblock %}